export const fileIconMap = {
    folder: "fileIcons/folder.png",
    jpg: "fileIcons/jpg.png",
    png: "fileIcons/png.png",
    svg: "fileIcons/svg.png",
    xls: "fileIcons/excel.png",
    xlsx: "fileIcons/excel.png",
    exe: "fileIcons/exe.png",
    txt: "fileIcons/txt.png",
    mp3: "fileIcons/mp3.png",
    mp4: "fileIcons/mp4.png",
    pdf: "fileIcons/pdf.png",
    ppt: "fileIcons/ppt.png",
    word: "fileIcons/word.png",
    doc: "fileIcons/word.png",
    docx: "fileIcons/word.png",
    zip: "fileIcons/zip.png",
    "": "fileIcons/file-fill.png",
};
